sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Execution_Order__c.field-meta.xml
<CustomField>
    <fullName>Execution_Order__c</fullName>
    <inlineHelpText>The order in which you wanted to execute the trigger handler class.</inlineHelpText>
    <label>Execution Order</label>
    <precision>10</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/HandlerClassName__c.field-meta.xml
<CustomField>
    <fullName>HandlerClassName__c</fullName>
    <label>Handler Class Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_After_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for After Delete Event Context.</inlineHelpText>
    <label>Is After Delete</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_After_Insert__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for After Insert Event Context.</inlineHelpText>
    <label>Is After Insert</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_After_Undelete__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Undelete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for After UnDelete Event Context.</inlineHelpText>
    <label>Is After Undelete</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_After_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_After_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for After Update Event Context.</inlineHelpText>
    <label>Is After Update</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_Before_Delete__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Delete__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for Before Delete Event Context.</inlineHelpText>
    <label>Is Before Delete</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_Before_Insert__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Insert__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for Before Event Context.</inlineHelpText>
    <label>Is Before Insert</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/Is_Before_Update__c.field-meta.xml
<CustomField>
    <fullName>Is_Before_Update__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>If True Enables the Trigger for Before Update Event Context.</inlineHelpText>
    <label>Is Before Update</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/isActive__c.field-meta.xml
<CustomField>
    <fullName>isActive__c</fullName>
    <defaultValue>false</defaultValue>
    <inlineHelpText>Indicates if the Trigger Handler is active or not</inlineHelpText>
    <label>Active?</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/triggerFramework/objects/Trigger_Handler__mdt/fields/ObjectName__c.field-meta.xml
<CustomField>
    <fullName>ObjectName__c</fullName>
    <inlineHelpText>Select the Object in which the trigger is on.</inlineHelpText>
    <label>Object Name</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Trigger_Handlers</relationshipLabel>
    <relationshipName>Trigger_Handlers</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdxsrc/triggerFramework/classes/TriggerDispatcher.cls
/**
 * @description       : 
 * @author            : Amit Singh
 * @group             : 
 * @last modified on  : 12-14-2020
 * @last modified by  : Amit Singh
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   12-06-2020   Amit Singh   Initial Version
**/
public with sharing class TriggerDispatcher {
    
    public static void run(String objectName){
        
        // Get All the Handler Setting for that Object
        List<Trigger_Handler__mdt> triggerEnablerList = getTriggerHandler(objectName);
        
        // Iterate Over the Handler Class based on the increasing Order and Execute the Trigger Handlers
        for(Trigger_Handler__mdt triggerEnabler : triggerEnablerList){
            // Check if the Handler is Active for the Operation or not
            if( (Boolean)triggerEnabler.get('Is_'+Trigger.operationType + '__c') ){
                processRecord( triggerEnabler.HandlerClassName__c );
            }
        }
    }
    
    private static void processRecord(String HandlerClassName){
        Type handlerType = Type.forName(HandlerClassName);
        TriggerInterface handler = (TriggerInterface)handlerType.newInstance();
        TriggerContext tc 		 = prepareContext();
        filterRecords(handler, tc);
    }
    
    private static void filterRecords(TriggerInterface handler, TriggerContext tc){
        List<sObject> filteredRecords = new List<sObject>();
        filteredRecords = (List<sObject>)handler.filterRecords(tc);
        System.debug(' filteredRecords \n '+ filteredRecords);
        // Call the execute method which will call the execute method of the Actual Handler Class
        execute(filteredRecords, handler, tc);
    }
    
    private static void execute(List<sObject> filteredRecords, TriggerInterface handler, TriggerContext tc){
        
        if(!filteredRecords.isEmpty()){
            handler.execute(filteredRecords, tc);
        }
        
    }

    private static List<Trigger_Handler__mdt> getTriggerHandler(String objectName){
        
        List<Trigger_Handler__mdt> triggerEnablerList = [SELECT Id, DeveloperName, Is_After_Delete__c, Is_After_Insert__c, Is_After_Undelete__c, Is_After_Update__c, Is_Before_Delete__c, 
                                                        		Is_Before_Insert__c, Is_Before_Update__c, Label, MasterLabel, HandlerClassName__c, Execution_Order__c, isActive__c
                                                        FROM Trigger_Handler__mdt 
                                                        WHERE ObjectName__r.QualifiedApiName =: objectName
                                                        AND isActive__c = TRUE
                                                        ORDER BY Execution_Order__c ASC];
        return triggerEnablerList;
        
    }
    
    private static TriggerContext prepareContext(){
        
        TriggerContext tc = new TriggerContext(
            Trigger.new, Trigger.Old, Trigger.newMap, Trigger.oldMap, Trigger.isExecuting,
            Trigger.isBefore && Trigger.isInsert, Trigger.isBefore && Trigger.isUpdate, Trigger.isBefore && Trigger.isDelete,
            Trigger.isAfter && Trigger.isInsert, Trigger.isAfter && Trigger.isUpdate, Trigger.isAfter && Trigger.isDelete,
            Trigger.isAfter && Trigger.isUnDelete
        );
        return tc;
        
    }

}