sfdxsrc/errorHandling/objects/System_Event__c/System_Event__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store All the events happening inside our app exchange application.</description>
    <label>System Event</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>System Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Additional_Email__c.field-meta.xml
<CustomField>
    <fullName>Additional_Email__c</fullName>
    <description>Provide the email list comma-separated if there are multiple emails.</description>
    <inlineHelpText>Provide the email list comma-separated if there are multiple emails.</inlineHelpText>
    <label>Additional Email</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>The name of the Component Apex, Flow &amp; Process or any other</description>
    <inlineHelpText>The name of the Component Apex, Flow &amp; Process or any other</inlineHelpText>
    <label>Component Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Email_Sent_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Email_Sent_DateTime__c</fullName>
    <inlineHelpText>The Timestamp when the email was sent</inlineHelpText>
    <label>Email Sent DateTime</label>
    <type>DateTime</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Email_Subject__c.field-meta.xml
<CustomField>
    <fullName>Email_Subject__c</fullName>
    <description>The subject of the Email if Log needs to be sent.</description>
    <inlineHelpText>The subject of the Email if Log needs to be sent.</inlineHelpText>
    <label>Email Subject</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Event_Level__c.field-meta.xml
<CustomField>
    <fullName>Event_Level__c</fullName>
    <description>The status of System Event Log.</description>
    <inlineHelpText>The status of System Event Log.</inlineHelpText>
    <label>Event Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Success Warning</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
                <isActive>false</isActive>
                <label>Exception</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>The Short message about the process of the System Event is created</description>
    <inlineHelpText>The Short message about the process of the System Event is created</inlineHelpText>
    <label>Message</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message_Rich_Text_02__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text_02__c</fullName>
    <description>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</description>
    <inlineHelpText>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</inlineHelpText>
    <label>Message Rich Text 02</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message_Rich_Text_03__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text_03__c</fullName>
    <inlineHelpText>The additional set of messages if required.</inlineHelpText>
    <label>Message Rich Text 03</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text__c</fullName>
    <description>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</description>
    <inlineHelpText>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</inlineHelpText>
    <label>Message Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Permission_Set__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set__c</fullName>
    <description>All the Permission set which are assigned to the User who created the System Event Record.</description>
    <inlineHelpText>All the Permission set which are assigned to the User who created the System Event Record.</inlineHelpText>
    <label>Permission Set</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Permission_Set_Group__c.field-meta.xml
<CustomField>
    <fullName>Permission_Set_Group__c</fullName>
    <inlineHelpText>The List of all the permission set Group the user is part of.</inlineHelpText>
    <label>Permission Set Group</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Public_Group_Membership__c.field-meta.xml
<CustomField>
    <fullName>Public_Group_Membership__c</fullName>
    <inlineHelpText>The list of all the public groups, that are associated with the user who has created the System Event Record.</inlineHelpText>
    <label>Public Group Membership</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Queue_Membership__c.field-meta.xml
<CustomField>
    <fullName>Queue_Membership__c</fullName>
    <inlineHelpText>List of All the Queues where user is associated with</inlineHelpText>
    <label>Queue Membership</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Send_Email__c.field-meta.xml
<CustomField>
    <fullName>Send_Email__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Check this checkbox if the Event log is worth sending to the users.</description>
    <inlineHelpText>Check this checkbox if the Event log is worth sending to the users.</inlineHelpText>
    <label>Send Email</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <inlineHelpText>The type of the component</inlineHelpText>
    <label>Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Aura</fullName>
            </value>
            <value>
                <fullName>LWC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>The user who created the System Event Log.</description>
    <inlineHelpText>The user who created the System Event Log.</inlineHelpText>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>System_Events</relationshipName>
    <type>Lookup</type>
</CustomField>

sfdxsrc/errorHandling/classes/Logger.cls
/**
 * @description       : 
 * @author            : Amit Singh
 * @group             : 
 * @last modified on  : 03-23-2021
 * @last modified by  : Amit Singh
 * Modifications Log 
 * Ver   Date         Author       Modification
 * 1.0   03-23-2021   Amit Singh   Initial Version
**/
global without sharing class Logger {

    private String message;
    private String componentName;
    private String eventLevel;
    private String typex;
    
    public  System_Event__c logRecord { get; set; }
    
    @InvocableMethod(label='Log System Event')
    global static List<ErrorLog> convertLeads(List<ErrorLog> requests) {
        ErrorLog request = requests.get(0);
        Logger logObject = new Logger(request.message, request.componentName, request.eventLevel, request.typex);
        logObject.log(UserInfo.getUserId(), request.richTextMessage, request.richTextMessage1, request.richTextMessage2);
        return requests;
    }
    
    global Logger(String message, String componentName, String eventLevel, String typex){
        this.message = message;
        this.componentName = componentName;
        this.eventLevel = eventLevel;
        this.typex = typex;
        logRecord = new System_Event__c();
    }

    global void log(String userId, String richTextMessage, String richTextMessage1, String richTextMessage2){
        prepareEvent(userId, richTextMessage, richTextMessage1, richTextMessage2);
        List<System_Event__c> newLogs = new List<System_Event__c>();
        newLogs.add(logRecord);
        SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, newLogs );
        insert securityDecision.getRecords();
    }
    
    global void sendLogEmail(String userId, String emailBody, List<String> emails, String subject){
        prepareEvent(userId, emailBody, '', '');
        logRecord.Send_Email__c = true;
        logRecord.Email_Sent_DateTime__c = System.now();
        logRecord.Additional_Email__c = String.join(emails, ':');
        logRecord.Email_Subject__c	= subject;
        List<System_Event__c> newLogs = new List<System_Event__c>();
        newLogs.add(logRecord);
        SObjectAccessDecision securityDecision = Security.stripInaccessible(AccessType.CREATABLE, newLogs );
        insert securityDecision.getRecords();
        
        sendEmail(emails, subject, emailBody);
    }
    
    private void sendEmail(List<String> toAddresses, String subject, String content){
        Messaging.SingleEmailMessage semail = new Messaging.SingleEmailMessage();
        semail.setToAddresses(toAddresses);
        semail.setSubject(subject);
        semail.setHtmlBody(content);
        if( !Test.isRunningTest() ){
            Messaging.sendEmail(new Messaging.SingleEmailMessage[] { semail });
        }
        
    }
    private List<String> getPermissionSets(){
        String permSet = '| ';
        String permGroups = '| ';
        for(PermissionSetAssignment perm : [SELECT Id, PermissionSet.Name, PermissionSetGroup.DeveloperName 
                                        FROM PermissionSetAssignment 
                                        WHERE AssigneeId =: UserInfo.getUserId()
                                        WITH SECURITY_ENFORCED ]){
            permSet += perm.PermissionSet.Name+' | ';
            if( null != perm.PermissionSetGroup.DeveloperName ){
                permGroups += perm.PermissionSetGroup.DeveloperName+' | ';
            }
        }
        List<String> groups = new List<String>();
        groups.add(permSet);
        groups.add(permGroups);
        return groups;
    }
    
    private String getGroupMembership(){
        String groups = '| ';
        for(GroupMember gm : [SELECT Id, Group.DeveloperName FROM GroupMember WHERE UserOrGroupId =: UserInfo.getUserId() AND Group.Type = 'Regular' WITH SECURITY_ENFORCED ]){
            if( null != gm.Group.DeveloperName ){
                groups += gm.Group.DeveloperName+' | ';
            }
        }
        return groups;
    }
    private String getQueueMembership(){
        String queues = '| ';
        for(GroupMember gm : [SELECT Id, Group.DeveloperName FROM GroupMember WHERE UserOrGroupId =: UserInfo.getUserId() AND Group.Type = 'Queue' WITH SECURITY_ENFORCED ]){
            if( null != gm.Group.DeveloperName ){
                queues += gm.Group.DeveloperName+' | ';
            }
        }
        return queues;
    }
    
    private System_Event__c prepareLogger(){
        logRecord.Message__c = message;
        logRecord.Component_Name__c = componentName;
        logRecord.Type__c = typex;
        logRecord.Event_Level__c = eventLevel;
        return logRecord;
    }
    
    private System_Event__c prepareEvent(String userId, String richTextMessage, String richTextMessage1, String richTextMessage2){
        prepareLogger();
        logRecord.User__c = userId;
        logRecord.Message_Rich_Text__c = richTextMessage;
        logRecord.Message_Rich_Text_02__c = richTextMessage1;
        logRecord.Message_Rich_Text_03__c = richTextMessage2;
        logRecord.Queue_Membership__c = getQueueMembership();
        logRecord.Public_Group_Membership__c = getGroupMembership();
        
        List<String> permissionSets = getPermissionSets();
        
        logRecord.Permission_Set_Group__c = permissionSets.get(1);
        logRecord.Permission_Set__c		= permissionSets.get(0);
        return logRecord;
    }
    
    global class ErrorLog {
        @InvocableVariable(required=true)
        global String message;
        @InvocableVariable(required=true)
        global String componentName;
        @InvocableVariable(required=true)
        global String eventLevel;
        @InvocableVariable(required=true)
        global String typex;
        
        @InvocableVariable
        global String richTextMessage;
        @InvocableVariable
        global String richTextMessage1;
        @InvocableVariable
        global String richTextMessage2;
    }
}