sfdxsrc/errorHandling/objects/System_Event__c/System_Event__c.object-meta.xml
<CustomObject>
    <description>This object will be used to store All the events happening inside our app exchange application.</description>
    <label>System Event</label>
    <nameField>
        <displayFormat>SE-{000000}</displayFormat>
        <label>System Event</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>System Events</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Component_Name__c.field-meta.xml
<CustomField>
    <fullName>Component_Name__c</fullName>
    <description>The name of the Component Apex, Flow &amp; Process or any other</description>
    <inlineHelpText>The name of the Component Apex, Flow &amp; Process or any other</inlineHelpText>
    <label>Component Name</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Component_Type__c.field-meta.xml
<CustomField>
    <fullName>Component_Type__c</fullName>
    <description>Stores the type of automation process component this system event occurred within.</description>
    <inlineHelpText>Choose the type of automation process component this system event occurred within.</inlineHelpText>
    <label>Component Type</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Apex</fullName>
            </value>
            <value>
                <fullName>Flow</fullName>
            </value>
            <value>
                <fullName>External Interface</fullName>
            </value>
            <value>
                <fullName>Process Builder</fullName>
            </value>
            <value>
                <fullName>Workflow</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Event_DateTime__c.field-meta.xml
<CustomField>
    <fullName>Event_DateTime__c</fullName>
    <inlineHelpText>Holds the time stamp when the log was generated.</inlineHelpText>
    <label>Event Date/Time</label>
    <required>true</required>
    <type>DateTime</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Event_Level__c.field-meta.xml
<CustomField>
    <fullName>Event_Level__c</fullName>
    <description>The status of System Event Log.</description>
    <inlineHelpText>The status of System Event Log.</inlineHelpText>
    <label>Event Level</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Error</fullName>
            </value>
            <value>
                <fullName>Success</fullName>
            </value>
            <value>
                <fullName>Warning</fullName>
            </value>
            <value>
                <fullName>Information</fullName>
            </value>
            <value>
                <fullName>Success Warning</fullName>
            </value>
            <value>
                <fullName>Exception</fullName>
                <isActive>false</isActive>
                <label>Exception</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message_Rich_Text_02__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text_02__c</fullName>
    <description>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</description>
    <inlineHelpText>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</inlineHelpText>
    <label>Message Rich Text 02</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sfdxsrc/errorHandling/objects/System_Event__c/fields/Message_Rich_Text__c.field-meta.xml
<CustomField>
    <fullName>Message_Rich_Text__c</fullName>
    <description>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</description>
    <inlineHelpText>A rich-text message describing the nature of this event. This rich-text message can include HTML formatting, hyperlinks, etc.</inlineHelpText>
    <label>Message Rich Text</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

sfdxsrc/errorHandling/classes/SystemEventHandler.cls
global with sharing class SystemEventHandler {

    global static void logSystemEvent(String message1, String message2, String eventLevel, String componentName, String componentType){
        System_Event__c systemEvent = new System_Event__c(
        	Component_Type__c 		= componentType,
            Component_Name__c 		= componentName,
            Event_Level__c  		= eventLevel,
            Message_Rich_Text__c    = message1,
            Message_Rich_Text_02__c = message2,
            Event_DateTime__c		= System.now()
        );
        insert systemEvent;
    }
}