sfdxsrc/genericDataTable/objects/Data_Table__mdt/Data_Table__mdt.object-meta.xml
<CustomObject>
    <description>This metadata is used to store the settings related to the generic data table.</description>
    <label>Data Table</label>
    <pluralLabel>Data Table</pluralLabel>
</CustomObject>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Default_Fields__c.field-meta.xml
<CustomField>
    <fullName>Default_Fields__c</fullName>
    <description>Holds the field API name which we do not want to show on the table as columns but still want to query.</description>
    <inlineHelpText>Comma-separated field API name to query along with columns.</inlineHelpText>
    <label>Default Fields</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Default_Page_Size__c.field-meta.xml
<CustomField>
    <fullName>Default_Page_Size__c</fullName>
    <description>Holds the default length of the table. i.e. the number of rows to be shown on each page.</description>
    <label>Default Page Size</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Object_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Object_API_Name__c</fullName>
    <description>Holds the API name of Object from where we need to pull the data.</description>
    <label>Object API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Paging_Picklist_Values__c.field-meta.xml
<CustomField>
    <fullName>Paging_Picklist_Values__c</fullName>
    <description>Comma-separated value for paging picklist.i.e 10,20,30</description>
    <inlineHelpText>Comma-separated value for paging picklist.i.e 10,20,30</inlineHelpText>
    <label>Paging Picklist Values</label>
    <type>TextArea</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Show_Pagination__c.field-meta.xml
<CustomField>
    <fullName>Show_Pagination__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if we want Pagination.</description>
    <label>Show Pagination</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Show_Paging_Picklist__c.field-meta.xml
<CustomField>
    <fullName>Show_Paging_Picklist__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if we want Paging Picklist.</description>
    <label>Show Paging Picklist</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Show_Search__c.field-meta.xml
<CustomField>
    <fullName>Show_Search__c</fullName>
    <defaultValue>false</defaultValue>
    <description>True if we want to search.</description>
    <label>Show Search</label>
    <type>Checkbox</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Sort_By__c.field-meta.xml
<CustomField>
    <fullName>Sort_By__c</fullName>
    <description>Holds default Sort Field API Name.</description>
    <label>Sort By</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Sort_Direction__c.field-meta.xml
<CustomField>
    <fullName>Sort_Direction__c</fullName>
    <label>Sort Direction</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>asc</fullName>
                <default>true</default>
                <label>ASC</label>
            </value>
            <value>
                <fullName>desc</fullName>
                <label>DESC</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table__mdt/fields/Table_Key_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Table_Key_Field_API_Name__c</fullName>
    <defaultValue>&quot;Id&quot;</defaultValue>
    <label>Table Key Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/Data_Table_Content__mdt.object-meta.xml
<CustomObject>
    <description>Holds the columns we want to show on the data table.</description>
    <label>Data Table Content</label>
    <pluralLabel>Data Table Contents</pluralLabel>
</CustomObject>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/Data_Table__c.field-meta.xml
<CustomField>
    <fullName>Data_Table__c</fullName>
    <description>Holds the parent Data Table name.</description>
    <label>Data Table</label>
    <referenceTo>Data_Table__mdt</referenceTo>
    <relationshipLabel>Data Table Contents</relationshipLabel>
    <relationshipName>Data_Table_Contents</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/DataType__c.field-meta.xml
<CustomField>
    <fullName>DataType__c</fullName>
    <description>Holds data type of field to be shown on the data table.</description>
    <label>DataType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Currency</fullName>
                <default>true</default>
                <label>Currency</label>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>date-local</fullName>
            </value>
            <value>
                <fullName>email</fullName>
            </value>
            <value>
                <fullName>number</fullName>
            </value>
            <value>
                <fullName>percent</fullName>
            </value>
            <value>
                <fullName>phone</fullName>
            </value>
            <value>
                <fullName>text</fullName>
            </value>
            <value>
                <fullName>url</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>Field_API_Name__c</fullName>
    <description>Holds API Name of Field.</description>
    <label>Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/Sequence__c.field-meta.xml
<CustomField>
    <fullName>Sequence__c</fullName>
    <description>Holds sequence of the column.</description>
    <label>Sequence</label>
    <precision>2</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/URL_Label_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>URL_Label_Field_API_Name__c</fullName>
    <description>Holds the API name of hyperlink label.</description>
    <inlineHelpText>API Name of the field which comes on the label of Hyperlink.</inlineHelpText>
    <label>URL Label Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/objects/Data_Table_Content__mdt/fields/URL_Target_Field_API_Name__c.field-meta.xml
<CustomField>
    <fullName>URL_Target_Field_API_Name__c</fullName>
    <description>Holds the API name of hyperlink target.</description>
    <inlineHelpText>API Name of the field which indicates the link&apos;s destination.</inlineHelpText>
    <label>URL Target Field API Name</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

sfdxsrc/genericDataTable/classes/GenericDataTableControllerHelper.cls
/*
* This is the helper class for GenericDataTableController contains the variables and wrapper.
*/

public with sharing class GenericDataTableControllerHelper {
    @TestVisible static private Map<String,List<sObject>> customMetadataRecordsMap = new Map<String,List<sObject>>();    
    public static final String DATA_TABLE_QUERY_FIELDS = 'Object_API_Name__c, Show_Pagination__c, Default_Fields__c, Default_Page_Size__c, Sort_By__c, Sort_Direction__c, Show_Search__c, Show_Paging_Picklist__c, Paging_Picklist_Values__c, Table_Key_Field_API_Name__c';
    public static final String CHILD_QUERY_FIELDS = 'MasterLabel, DataType__c, Field_API_Name__c, Sequence__c,URL_Label_Field_API_Name__c, URL_Target_Field_API_Name__c';
    public static final String PARENT_METADATA_API_NAME = 'Data_Table__mdt';
    public static final String CHILD_RELATIONSHIP_NAME = 'Data_Table_Contents__r';
    
    /*
    * This Helper method is use to get all Parent & Child metadata using the given metadata name.
    */
    public InitializeWrapper initialize(String metaQuery, String metaName){        
        InitializeWrapper initValue = new InitializeWrapper();
        string query = metaQuery+' WHERE DeveloperName =: metaName LIMIT 1';
        initValue.metadataRecords.addAll((List<Data_Table__mdt>)getCustomMetadataRecords(query,metaName));
        if(!initValue.metadataRecords.isEmpty()){
            if(String.isNotEmpty(initValue.metadataRecords[0].Default_Fields__c)){
                initValue.dataParse.fieldToQuery.addAll(initValue.metadataRecords[0].Default_Fields__c.split(','));
            }
            if(!initValue.metadataRecords[0].Data_Table_Contents__r.isEmpty()){
                initValue.cols.addAll(initValue.metadataRecords[0].Data_Table_Contents__r);
            }
        }
        return initValue;
    }
    
    /*
    * This method is use for populate the check variables.
    */
    public DataParserWrapper dataParser(List<Data_Table_Content__mdt>cols){
        DataParserWrapper parsedData = new DataParserWrapper();
        if(!cols.isEmpty()){
            for(Data_Table_Content__mdt col : cols){
                if(col.DataType__c == 'date-local'){
                    parsedData.dateIdentifier.add(col.Field_API_Name__c);
                    parsedData.fieldToQuery.add(col.Field_API_Name__c);
                    parsedData.sortMapInner.put(col.Field_API_Name__c, col.Field_API_Name__c);                    
                }else if(col.DataType__c == 'url'){
                    String dummyValue = arrangeDummies(col.URL_Target_Field_API_Name__c, false);
                    String dummyLabel = arrangeDummies(col.URL_Label_Field_API_Name__c, true);
                    parsedData.fieldToQuery.add(col.URL_Target_Field_API_Name__c);
                    parsedData.fieldToQuery.add(col.URL_Label_Field_API_Name__c);
                    parsedData.actualToDummyHyperLink.put(col.URL_Target_Field_API_Name__c, dummyValue);
                    parsedData.actualToDummyHyperLink.put(col.URL_Label_Field_API_Name__c, dummyLabel);
                    parsedData.urlIdentifier.add(dummyValue);
                    parsedData.sortMapInner.put(dummyValue, dummyLabel);
                }else{
                    parsedData.fieldToQuery.add(col.Field_API_Name__c);
                    parsedData.sortMapInner.put(col.Field_API_Name__c, col.Field_API_Name__c);
                }
            }
        }
        return parsedData;
    }
    
    /*
    This method is use to handle hyperlink for table.
    */
    public static String arrangeDummies(String valueToChange, Boolean isLabel){
        String changedVal;
        if(valueToChange.contains('.')){
            changedVal = valueToChange.substringBefore('.');
        }else{
            changedVal = valueToChange.contains('__c') ? valueToChange.substringBefore('__c') : valueToChange;
        }
        return changedVal +'_'+ (isLabel ? 'LABEL' : 'VALUE');
    }
    
    /*
    * This method is use to fetch metadata records.
    */
    private List<sObject> getCustomMetadataRecords(String query, String metaName){//NOSONAR
        if(!customMetadataRecordsMap.containsKey(query)){
            customMetadataRecordsMap.put(query,Database.query(String.escapeSingleQuotes(query)));
        }
        return customMetadataRecordsMap.get(query);
    }
    
    public class InitializeWrapper{
        public List<Data_Table__mdt> metadataRecords;
        public List<Data_Table_Content__mdt> cols;
        public DataParserWrapper dataParse;
        public InitializeWrapper(){
            this.metadataRecords = new List<Data_Table__mdt>();
            this.cols = new List<Data_Table_Content__mdt>();
            this.dataParse = new DataParserWrapper();
        }
    }
    
    public class DataParserWrapper{
        public Set<String> fieldToQuery;
        public Map<String,String> actualToDummyHyperLink;
        public Map<String,String> sortMapInner;
        public Set<String> urlIdentifier;
        public Set<String> dateIdentifier;
        
        public DataParserWrapper(){
            this.fieldToQuery = new Set<String>();
            this.actualToDummyHyperLink = new Map<String,String>();
            this.sortMapInner = new Map<String,String>();
            this.urlIdentifier = new Set<String>();
            this.dateIdentifier = new Set<String>();
        }
    }
}